// <auto-generated />
namespace CodeFirstApproach.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class TestTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TestTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201704291131380_TestTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
